language: go
go:
- 1.14.x
env:
  matrix:
  - GO111MODULE=on
  global:
    secure: XqRwGBuPCeB6zybXxIGL2bzIgItfHZKxP94kJLBqLtbaAIx8UK+q4dYTAGO8v7UyHiO9BmA6P4gRPGjF0Ngls7+B4eLxsGO1eGT161IcNAZUFI8RYgoo868paMEOxp8zqCTxDntfGTk7/2wr0dwGJuAbXqw1ShUgpNG9yOqLbknR4V7vZkNJBVe7Y6ScMFemytUdcSa7cw59ZrM1uOveekYU/om3q8LYAMCV7W8v8E6hochxz/9u0WwGerj67O6AtsSp5AWWreMIt8IjMo3cq0BPCwosAmxAtBVKMYT1p9uVkrSWx/xd+ybemfRc4/XaDOb7L5v0YSzY3eCE1wXXd0lHVf9ydHRPMC+2+tV/BiU0RSxr74KMWltW8E36Y0pEczB2hAfedQYD4eJoYgJElka7i70LYjnLs6hiqGQKsjZA+lkGWC1SFx56QqH/Y1Y8dg3A9hAZJn1E+ReompI8NbERBBa/DXuOFDO+hzufdnZR5wtsxDnu/msMsViVTDvoRfd+80Ua0xmGeGLJVDaXNDMkLDO6pWZYWClzyy9mMY3RI886ube+2eYBnG/pVqwKk/BXFt84rq5HH0MGDWIdY5T7o8YS03bFQIvlVgMNXCthcsYqPDvriAvFSST+vZQtyp0hIC+ydCqMu2d2T45ApOyf9XZwzCbEXEgRvu+0HiQ=
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic
install:
- go get -v
before_deploy: make build-all
deploy:
  provider: releases
  api_key:
    secure: XqRwGBuPCeB6zybXxIGL2bzIgItfHZKxP94kJLBqLtbaAIx8UK+q4dYTAGO8v7UyHiO9BmA6P4gRPGjF0Ngls7+B4eLxsGO1eGT161IcNAZUFI8RYgoo868paMEOxp8zqCTxDntfGTk7/2wr0dwGJuAbXqw1ShUgpNG9yOqLbknR4V7vZkNJBVe7Y6ScMFemytUdcSa7cw59ZrM1uOveekYU/om3q8LYAMCV7W8v8E6hochxz/9u0WwGerj67O6AtsSp5AWWreMIt8IjMo3cq0BPCwosAmxAtBVKMYT1p9uVkrSWx/xd+ybemfRc4/XaDOb7L5v0YSzY3eCE1wXXd0lHVf9ydHRPMC+2+tV/BiU0RSxr74KMWltW8E36Y0pEczB2hAfedQYD4eJoYgJElka7i70LYjnLs6hiqGQKsjZA+lkGWC1SFx56QqH/Y1Y8dg3A9hAZJn1E+ReompI8NbERBBa/DXuOFDO+hzufdnZR5wtsxDnu/msMsViVTDvoRfd+80Ua0xmGeGLJVDaXNDMkLDO6pWZYWClzyy9mMY3RI886ube+2eYBnG/pVqwKk/BXFt84rq5HH0MGDWIdY5T7o8YS03bFQIvlVgMNXCthcsYqPDvriAvFSST+vZQtyp0hIC+ydCqMu2d2T45ApOyf9XZwzCbEXEgRvu+0HiQ=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: JieTrancender/iv-go
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6cfc1298-5dd6-4958-b553-e26b2fdea603
