iv:
  jwt_secret: aSBsaWtlLCBpIGxvdmUu
  welcome: "i like, i love."

server:
  run_mode: debug
  http_port: 8080
  read_timeout: 60
  write_timeout: 60

database:
  type: mysql
  user: root
  password: 123456
  host: 192.168.3.212:3306
  name: iv-go
  table_prefix: iv_

redis:
  host: 192.168.3.212:6379
  password: 123456
  max_idle: 30
  max_active: 30
  idle_timeout: 200
